annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: you can find the changedlog in link
    - kind: add
      description: The full release notes are available here. Note that the chart versions match the software versions
    - kind: add
      description: The full release notes are available here. 1

apiVersion: v2
type: application

name: redis-enterprise-operator
description: A Helm chart for Redis Enterprise Operator for Kubernetes

version: 7.11.4-12
appVersion: 7.11.4-12

home: https://redis.io
icon: https://redis.io/wp-content/uploads/2024/04/Logotype.svg
keywords:
- redis
- database
maintainers:
- name: Redis
  url: https://redis.com/company/contact/
